### ISSUE TITLE
ui-router-core.git does not exist

### ISSUE THREAD

**Issue by josefK128** [angular-ui/ui-router-ng2#1]
* clone returns 'Repository not found' 
* URL returns 404

**Comment by christopherthielen** [comment]
Hi @josefK128 We decided to move to a single unified repository.  https://github.com/angular-ui/ui-router/tree/master/src now contains ui-router-core, angular-ui-router (ng1) and ui-router-ng2.  If you'd like to play with the ng2 code today (I think it's not quite ready for public consumption), you can 

```
git clone https://github.com/angular-ui/ui-router.git
cd ui-router
npm install
grunt
```
`build/ui-router-ng2.js` should contain the built version.
